// Word packs for "Words with Pipo". Each word: a stable id, an emoji picture,
// the English word and the Spanish word (nouns with their article: "el perro").
// Colours also carry a `swatch` so they show as a painted dot, not an emoji.
// To add a language: add a field (e.g. `fr`) to every word and pack name.
const WORD_PACKS = [
  {
    id: "animals",
    emoji: "🐶",
    color: "#ffb570",
    name: { en: "Animals", es: "Animales" },
    words: [
      { id: "dog", emoji: "🐶", en: "dog", es: "el perro" },
      { id: "cat", emoji: "🐱", en: "cat", es: "el gato" },
      { id: "cow", emoji: "🐮", en: "cow", es: "la vaca" },
      { id: "pig", emoji: "🐷", en: "pig", es: "el cerdo" },
      { id: "horse", emoji: "🐴", en: "horse", es: "el caballo" },
      { id: "sheep", emoji: "🐑", en: "sheep", es: "la oveja" },
      { id: "duck", emoji: "🦆", en: "duck", es: "el pato" },
      { id: "lion", emoji: "🦁", en: "lion", es: "el león" },
      { id: "elephant", emoji: "🐘", en: "elephant", es: "el elefante" },
      { id: "monkey", emoji: "🐵", en: "monkey", es: "el mono" },
      { id: "frog", emoji: "🐸", en: "frog", es: "la rana" },
      { id: "fish", emoji: "🐟", en: "fish", es: "el pez" },
    ],
  },
  {
    id: "food",
    emoji: "🍎",
    color: "#ff9fb8",
    name: { en: "Food", es: "Comida" },
    words: [
      { id: "apple", emoji: "🍎", en: "apple", es: "la manzana" },
      { id: "banana", emoji: "🍌", en: "banana", es: "el plátano" },
      { id: "grapes", emoji: "🍇", en: "grapes", es: "las uvas" },
      { id: "strawberry", emoji: "🍓", en: "strawberry", es: "la fresa" },
      { id: "carrot", emoji: "🥕", en: "carrot", es: "la zanahoria" },
      { id: "bread", emoji: "🍞", en: "bread", es: "el pan" },
      { id: "cheese", emoji: "🧀", en: "cheese", es: "el queso" },
      { id: "egg", emoji: "🥚", en: "egg", es: "el huevo" },
      { id: "milk", emoji: "🥛", en: "milk", es: "la leche" },
      { id: "cake", emoji: "🎂", en: "cake", es: "la tarta" },
      { id: "ice-cream", emoji: "🍦", en: "ice cream", es: "el helado" },
      { id: "pizza", emoji: "🍕", en: "pizza", es: "la pizza" },
    ],
  },
  {
    id: "colours",
    emoji: "🎨",
    color: "#c3a6ff",
    name: { en: "Colours", es: "Colores" },
    words: [
      { id: "red", emoji: "🔴", swatch: "#f03e3e", en: "red", es: "rojo" },
      {
        id: "orange",
        emoji: "🟠",
        swatch: "#ff922b",
        en: "orange",
        es: "naranja",
      },
      {
        id: "yellow",
        emoji: "🟡",
        swatch: "#ffd43b",
        en: "yellow",
        es: "amarillo",
      },
      { id: "green", emoji: "🟢", swatch: "#40c057", en: "green", es: "verde" },
      { id: "blue", emoji: "🔵", swatch: "#228be6", en: "blue", es: "azul" },
      {
        id: "purple",
        emoji: "🟣",
        swatch: "#9c36b5",
        en: "purple",
        es: "morado",
      },
      { id: "pink", emoji: "🩷", swatch: "#f783ac", en: "pink", es: "rosa" },
      {
        id: "brown",
        emoji: "🟤",
        swatch: "#8d5a2b",
        en: "brown",
        es: "marrón",
      },
      { id: "black", emoji: "⚫", swatch: "#212529", en: "black", es: "negro" },
      {
        id: "white",
        emoji: "⚪",
        swatch: "#ffffff",
        en: "white",
        es: "blanco",
      },
    ],
  },
  {
    id: "body",
    emoji: "✋",
    color: "#ffd84d",
    name: { en: "My body", es: "El cuerpo" },
    words: [
      { id: "eye", emoji: "👁️", en: "eye", es: "el ojo" },
      { id: "ear", emoji: "👂", en: "ear", es: "la oreja" },
      { id: "nose", emoji: "👃", en: "nose", es: "la nariz" },
      { id: "mouth", emoji: "👄", en: "mouth", es: "la boca" },
      { id: "tongue", emoji: "👅", en: "tongue", es: "la lengua" },
      { id: "tooth", emoji: "🦷", en: "tooth", es: "el diente" },
      { id: "hand", emoji: "✋", en: "hand", es: "la mano" },
      { id: "arm", emoji: "💪", en: "arm", es: "el brazo" },
      { id: "leg", emoji: "🦵", en: "leg", es: "la pierna" },
      { id: "foot", emoji: "🦶", en: "foot", es: "el pie" },
    ],
  },
  {
    id: "home",
    emoji: "🏠",
    color: "#82c8ff",
    name: { en: "At home", es: "En casa" },
    words: [
      { id: "house", emoji: "🏠", en: "house", es: "la casa" },
      { id: "door", emoji: "🚪", en: "door", es: "la puerta" },
      { id: "window", emoji: "🪟", en: "window", es: "la ventana" },
      { id: "bed", emoji: "🛏️", en: "bed", es: "la cama" },
      { id: "chair", emoji: "🪑", en: "chair", es: "la silla" },
      { id: "sofa", emoji: "🛋️", en: "sofa", es: "el sofá" },
      { id: "bath", emoji: "🛁", en: "bath", es: "la bañera" },
      { id: "key", emoji: "🔑", en: "key", es: "la llave" },
      { id: "clock", emoji: "⏰", en: "clock", es: "el reloj" },
      { id: "book", emoji: "📖", en: "book", es: "el libro" },
      { id: "cup", emoji: "☕", en: "cup", es: "la taza" },
      { id: "spoon", emoji: "🥄", en: "spoon", es: "la cuchara" },
    ],
  },
  {
    id: "clothes",
    emoji: "👕",
    color: "#6ee0c0",
    name: { en: "Clothes", es: "La ropa" },
    words: [
      { id: "shirt", emoji: "👕", en: "shirt", es: "la camiseta" },
      { id: "dress", emoji: "👗", en: "dress", es: "el vestido" },
      { id: "jeans", emoji: "👖", en: "jeans", es: "los vaqueros" },
      { id: "shoe", emoji: "👞", en: "shoe", es: "el zapato" },
      { id: "boot", emoji: "👢", en: "boot", es: "la bota" },
      { id: "sock", emoji: "🧦", en: "sock", es: "el calcetín" },
      { id: "hat", emoji: "👒", en: "hat", es: "el sombrero" },
      { id: "cap", emoji: "🧢", en: "cap", es: "la gorra" },
      { id: "glove", emoji: "🧤", en: "glove", es: "el guante" },
      { id: "scarf", emoji: "🧣", en: "scarf", es: "la bufanda" },
      { id: "coat", emoji: "🧥", en: "coat", es: "el abrigo" },
      { id: "glasses", emoji: "👓", en: "glasses", es: "las gafas" },
    ],
  },
  {
    id: "nature",
    emoji: "🌳",
    color: "#9be58a",
    name: { en: "Nature", es: "Naturaleza" },
    words: [
      { id: "sun", emoji: "☀️", en: "sun", es: "el sol" },
      { id: "moon", emoji: "🌙", en: "moon", es: "la luna" },
      { id: "star", emoji: "⭐", en: "star", es: "la estrella" },
      { id: "cloud", emoji: "☁️", en: "cloud", es: "la nube" },
      { id: "rain", emoji: "🌧️", en: "rain", es: "la lluvia" },
      { id: "snow", emoji: "❄️", en: "snow", es: "la nieve" },
      { id: "rainbow", emoji: "🌈", en: "rainbow", es: "el arcoíris" },
      { id: "tree", emoji: "🌳", en: "tree", es: "el árbol" },
      { id: "flower", emoji: "🌸", en: "flower", es: "la flor" },
      { id: "leaf", emoji: "🍃", en: "leaf", es: "la hoja" },
      { id: "mountain", emoji: "⛰️", en: "mountain", es: "la montaña" },
      { id: "sea", emoji: "🌊", en: "sea", es: "el mar" },
    ],
  },
  {
    id: "vehicles",
    emoji: "🚗",
    color: "#ff9a8a",
    name: { en: "On the move", es: "Transportes" },
    words: [
      { id: "car", emoji: "🚗", en: "car", es: "el coche" },
      { id: "bus", emoji: "🚌", en: "bus", es: "el autobús" },
      { id: "train", emoji: "🚂", en: "train", es: "el tren" },
      { id: "plane", emoji: "✈️", en: "plane", es: "el avión" },
      { id: "boat", emoji: "⛵", en: "boat", es: "el barco" },
      { id: "bike", emoji: "🚲", en: "bike", es: "la bicicleta" },
      { id: "motorbike", emoji: "🏍️", en: "motorbike", es: "la moto" },
      { id: "truck", emoji: "🚚", en: "truck", es: "el camión" },
      { id: "tractor", emoji: "🚜", en: "tractor", es: "el tractor" },
      { id: "helicopter", emoji: "🚁", en: "helicopter", es: "el helicóptero" },
      { id: "rocket", emoji: "🚀", en: "rocket", es: "el cohete" },
      { id: "ambulance", emoji: "🚑", en: "ambulance", es: "la ambulancia" },
    ],
  },
];

if (typeof module !== "undefined") module.exports = WORD_PACKS;
