// Every visible string of the Cube game, in English and Spanish.
// Strings that mention the buddy are functions (name, treats) => …; colours
// are passed in already translated (see colour()).
const MOVE_EN = {
  R: ["Turn the RIGHT side UP", "↑"],
  "R'": ["Turn the RIGHT side DOWN", "↓"],
  R2: ["Turn the RIGHT side twice", "↑↑"],
  L: ["Turn the LEFT side DOWN", "↓"],
  "L'": ["Turn the LEFT side UP", "↑"],
  L2: ["Turn the LEFT side twice", "↓↓"],
  U: ["Turn the TOP to the LEFT", "←"],
  "U'": ["Turn the TOP to the RIGHT", "→"],
  U2: ["Turn the TOP twice", "←←"],
  D: ["Turn the BOTTOM to the RIGHT", "→"],
  "D'": ["Turn the BOTTOM to the LEFT", "←"],
  D2: ["Turn the BOTTOM twice", "→→"],
  F: ["Turn the FRONT like a steering wheel, to the right", "↻"],
  "F'": ["Turn the FRONT like a steering wheel, to the left", "↺"],
  F2: ["Turn the FRONT twice", "↻↻"],
  B: ["Turn the BACK: its top goes LEFT", "↺"],
  "B'": ["Turn the BACK: its top goes RIGHT", "↻"],
  B2: ["Turn the BACK twice", "↺↺"],
  M: ["Turn the MIDDLE slice DOWN", "↓"],
  "M'": ["Turn the MIDDLE slice UP", "↑"],
  M2: ["Turn the MIDDLE slice twice", "↓↓"],
  E: ["Turn the MIDDLE row to the RIGHT", "→"],
  "E'": ["Turn the MIDDLE row to the LEFT", "←"],
  E2: ["Turn the MIDDLE row twice", "→→"],
  S: ["Turn the MIDDLE like a steering wheel, to the right", "↻"],
  "S'": ["Turn the MIDDLE like a steering wheel, to the left", "↺"],
  S2: ["Turn the MIDDLE slice twice", "↻↻"],
  x: ["Roll the WHOLE cube UP", "⤒"],
  "x'": ["Roll the WHOLE cube DOWN", "⤓"],
  x2: ["Roll the WHOLE cube over", "⤒⤒"],
  y: ["Turn the WHOLE cube to the LEFT", "⟲"],
  "y'": ["Turn the WHOLE cube to the RIGHT", "⟳"],
  y2: ["Turn the WHOLE cube half way round", "⟲⟲"],
  z: ["Tilt the WHOLE cube to the right", "↻"],
  "z'": ["Tilt the WHOLE cube to the left", "↺"],
  z2: ["Turn the WHOLE cube UPSIDE DOWN", "⇅"],
};
const MOVE_ES = {
  R: ["Gira el lado DERECHO hacia ARRIBA", "↑"],
  "R'": ["Gira el lado DERECHO hacia ABAJO", "↓"],
  R2: ["Gira el lado DERECHO dos veces", "↑↑"],
  L: ["Gira el lado IZQUIERDO hacia ABAJO", "↓"],
  "L'": ["Gira el lado IZQUIERDO hacia ARRIBA", "↑"],
  L2: ["Gira el lado IZQUIERDO dos veces", "↓↓"],
  U: ["Gira ARRIBA hacia la IZQUIERDA", "←"],
  "U'": ["Gira ARRIBA hacia la DERECHA", "→"],
  U2: ["Gira ARRIBA dos veces", "←←"],
  D: ["Gira ABAJO hacia la DERECHA", "→"],
  "D'": ["Gira ABAJO hacia la IZQUIERDA", "←"],
  D2: ["Gira ABAJO dos veces", "→→"],
  F: ["Gira el FRENTE como un volante, a la derecha", "↻"],
  "F'": ["Gira el FRENTE como un volante, a la izquierda", "↺"],
  F2: ["Gira el FRENTE dos veces", "↻↻"],
  B: ["Gira la cara de ATRÁS: su parte de arriba va a la IZQUIERDA", "↺"],
  "B'": ["Gira la cara de ATRÁS: su parte de arriba va a la DERECHA", "↻"],
  B2: ["Gira la cara de ATRÁS dos veces", "↺↺"],
  M: ["Gira la rodaja del MEDIO hacia ABAJO", "↓"],
  "M'": ["Gira la rodaja del MEDIO hacia ARRIBA", "↑"],
  M2: ["Gira la rodaja del MEDIO dos veces", "↓↓"],
  E: ["Gira la fila del MEDIO hacia la DERECHA", "→"],
  "E'": ["Gira la fila del MEDIO hacia la IZQUIERDA", "←"],
  E2: ["Gira la fila del MEDIO dos veces", "→→"],
  S: ["Gira el MEDIO como un volante, a la derecha", "↻"],
  "S'": ["Gira el MEDIO como un volante, a la izquierda", "↺"],
  S2: ["Gira la rodaja del MEDIO dos veces", "↻↻"],
  x: ["Rueda TODO el cubo hacia ARRIBA", "⤒"],
  "x'": ["Rueda TODO el cubo hacia ABAJO", "⤓"],
  x2: ["Rueda TODO el cubo hasta darle la vuelta", "⤒⤒"],
  y: ["Gira TODO el cubo hacia la IZQUIERDA", "⟲"],
  "y'": ["Gira TODO el cubo hacia la DERECHA", "⟳"],
  y2: ["Da media vuelta a TODO el cubo", "⟲⟲"],
  z: ["Inclina TODO el cubo hacia la derecha", "↻"],
  "z'": ["Inclina TODO el cubo hacia la izquierda", "↺"],
  z2: ["Pon TODO el cubo BOCA ABAJO", "⇅"],
};

const en = {
  docTitle: (name) => `Cube with ${name} 3D`,
  title: (name) => `Cube with ${name}`,
  menu: "Menu",
  menuLabel: "Back to the cube menu",
  colors: ["white", "red", "green", "yellow", "orange", "blue"],
  COLORS: ["WHITE", "RED", "GREEN", "YELLOW", "ORANGE", "BLUE"],
  size2: "2×2",
  size3: "3×3",
  sizeLabel: "Cube size",
  modePlay: "Play",
  modePlayAbout: "Twist it any way you like",
  modeGuide: "Solve with me",
  modeGuideAbout: (name) => `${name} shows you every move`,
  modeReal: "My real cube",
  modeRealAbout: "Paint your cube, then solve it",
  modeLearn: "Learn",
  modeLearnAbout: "One trick at a time, win stars",
  hello: (name) => `Hi! I'm ${name}. Let's twist!`,
  poke: [
    "Twist, twist! 🌀",
    "I love colours! 🎨",
    "You can do it! 💪",
    "Wheee! 🧊",
  ],
  buddyPoke: (name) => `${name}. Tap to say hi`,
  // moves
  moveText: MOVE_EN,
  soFaces: (c) => `so ${c} faces you`,
  soTop: (c) => `so ${c} is on top`,
  twice: "twice",
  // play toolbar
  scramble: "Mix",
  scrambleLabel: "Mix up the cube",
  undo: "Undo",
  redo: "Redo",
  reset: "Reset",
  resetLabel: "Make the cube new again",
  pad: "Buttons",
  padLabel: "Show or hide the turn buttons",
  timer: "Timer",
  timerLabel: "Show or hide the move counter and timer",
  helpMe: "Help me",
  helpMeLabel: "Solve this cube step by step",
  moves: (n) => `${n} ${n === 1 ? "move" : "moves"}`,
  wholeCube: "Whole cube",
  faceBtn: (text) => text,
  playTip: "Swipe a side to turn it. Drag around the cube to turn it all.",
  solvedPlay: "Solved! 🎉",
  solvedPlaySay: (name) => `You did it! ${name} is so proud!`,
  // guide
  stagesLabel: "Steps to solve the cube",
  stageOf: (i, n, name) => `Step ${i} of ${n}: ${name}`,
  stage3: [
    "White cross",
    "White corners",
    "Middle layer",
    "Yellow cross",
    "Yellow edges",
    "Yellow corners home",
    "Twist the corners",
  ],
  stage2: ["White layer", "Yellow corners home", "Twist the corners"],
  watch: "Show me",
  watchLabel: "Watch this move",
  skip: "Finish step",
  skipLabel: "Finish this step for me",
  didIt: "I did it",
  didItLabel: "I made this move on my cube",
  back: "Back",
  backLabel: "Go back one move",
  moveOf: (i, n) => `${i} / ${n}`,
  trick: {
    magic: "Magic move",
    right: "Right trick",
    left: "Left trick",
    ycross: "Cross trick",
    sune: "Swirl trick",
    corners: "Corner swap trick",
  },
  say: {
    hold: (c) => `Hold the cube with ${c} on top!`,
    cross: (c) => `Take the white–${c} piece home, next to the ${c} centre!`,
    corner: (a, b) => `Magic move time! Put the white–${a}–${b} corner home.`,
    flip: "Flip it! YELLOW goes on top now.",
    middle: (a, b) =>
      `Make a T, then slide the ${a}–${b} piece into the middle.`,
    pop: "This piece is stuck. Pop it out to the top first!",
    ycross: "Make a yellow cross on top with the cross trick.",
    yedges: "Match the yellow edges with their colours.",
    align: "Turn the top to line everything up!",
    yplace: "Send the yellow corners to their homes.",
    "hold-corner": "Hold a twisted corner at the front, on the right.",
    ytwist:
      "Magic move until yellow looks up! The bottom gets messy: don't worry.",
    "next-corner": "Turn ONLY the top to bring the next corner.",
    layer: (a, b) => `Magic move time! Put the white–${a}–${b} corner home.`,
  },
  oops: "Oops! Let's undo that.",
  oopsDir: "Nearly! The other way.",
  yay: ["Yes! ✨", "Great! 🌟", "Nice one! 👍", "Perfect! 💫"],
  stageDone: (stage) => `${stage}: done! 🎉`,
  stageTreat: (name, treats) => `${name} gets ${treats}!`,
  solvedGuide: "You solved the cube! 🎉",
  solvedGuideBody: (name, treats) =>
    `Amazing! ${name} is munching ${treats} to celebrate.`,
  again: "Again",
  newCube: "New cube",
  holdBadge: (top, front) => `Hold: ${top} on top, ${front} in front`,
  holdBadge2: "Keep holding it the same way",
  realTip: "Make each move on your real cube, then tap ✓.",
  // real cube painting
  paintTitle: "Paint your cube",
  paintStep: (i) => `Side ${i} of 6`,
  paintFace3: [
    "Hold the cube with WHITE on top and GREEN facing you. Paint the side you see.",
    "Turn the cube to the left ←. RED faces you now (WHITE still on top).",
    "Turn it to the left again ←. BLUE faces you.",
    "One more time to the left ←. ORANGE faces you.",
    "Turn it back so GREEN faces you, then tip the top towards you: WHITE faces you, GREEN at the bottom.",
    "Tip it the other way: YELLOW faces you, GREEN at the top.",
  ],
  paintFace2: [
    "Hold the cube any way you like. Paint the side that looks at you.",
    "Turn the cube to the left ←. Paint the new side.",
    "Turn it to the left again ←.",
    "One more time to the left ←.",
    "Turn it back to the first side, then tip the top towards you.",
    "Tip it the other way: the bottom faces you.",
  ],
  paletteLabel: "Paint colours",
  pickColor: (c) => `Paint ${c}`,
  cellLabel: (r, c, col) => `Row ${r}, column ${c}: ${col}`,
  blank: "not painted",
  next: "Next",
  prev: "Back",
  check: "Check my cube",
  clearFace: "Clear",
  left: (n) => `${n} left`,
  paintOk: "Your cube looks great! Let's solve it.",
  paintErr: {
    unpainted: "Some stickers are still grey. Paint them all!",
    count: (over, under) =>
      `There are too many ${over} stickers and not enough ${under}. Check the ${over} ones!`,
    centers:
      "The centre colours don't look right. Hold WHITE on top and GREEN in front.",
    corner: (cs) => `That corner can't exist: check its ${cs} stickers.`,
    edge: (cs) => `That edge can't exist: check its ${cs} stickers.`,
    twist: "One corner seems twisted. Check the corner stickers again!",
    flip: "One edge seems flipped. Check the edge stickers again!",
    parity: "Two pieces seem swapped. Check your painting again!",
  },
  paintErrTip:
    "If everything matches, your cube may have been taken apart and put back the wrong way. Ask a grown-up to help!",
  and: "and",
  errTitle: "Hmm, let's check",
  fix: "Fix it",
  // learn
  learnTitle: "Learn",
  lesson: (i) => `Lesson ${i}`,
  locked: "locked",
  lessonLabel: (i, name, stars, open) =>
    `Lesson ${i}: ${name}, ${stars} of 3 stars${open ? "" : ", locked"}`,
  lessonIntro: {
    cross:
      "Make a white cross on top. Each white edge goes next to its matching centre.",
    corners:
      "The magic move R' D' R D! Put a corner under its spot and repeat until it's home.",
    middle:
      "Make a T with an edge, then use the right trick or the left trick.",
    ycross:
      "Yellow on top. The cross trick F R U R' U' F' makes a yellow cross.",
    yedges: "The swirl trick R U R' U R U2 R' swaps the yellow edges.",
    yplace:
      "The corner swap trick U R U' L' U R' U' L moves three corners around.",
    ytwist:
      "Magic move again! Repeat it until yellow looks up, then turn only the top.",
    layer:
      "Build the white side with the magic move R' D' R D, one corner at a time.",
  },
  letsGo: "Let's go! 🚀",
  practice: (i, n) => `Practice ${i} of ${n}`,
  lessonDone: "Lesson done!",
  lessonStars: (s) =>
    s === 3
      ? "Three stars: you did every move yourself!"
      : s === 2
        ? "Two stars! Next time try without watching."
        : "One star! Next time try every move yourself.",
  nextLesson: "Next lesson",
  totalStars: (n, max) => `⭐ ${n} / ${max}`,
  flatNote: "Flat view: tap a side, then turn it with the arrows.",
  turnSide: (f) => `Turn ${f}`,
  faceNames: ["TOP", "RIGHT", "FRONT", "BOTTOM", "LEFT", "BACK"],
  cw: "clockwise",
  ccw: "counter-clockwise",
  view3d: "3D",
};

const es = {
  docTitle: (name) => `Cubo con ${name} 3D`,
  title: (name) => `Cubo con ${name}`,
  menu: "Menú",
  menuLabel: "Volver al menú del cubo",
  colors: ["blanco", "rojo", "verde", "amarillo", "naranja", "azul"],
  COLORS: ["BLANCO", "ROJO", "VERDE", "AMARILLO", "NARANJA", "AZUL"],
  size2: "2×2",
  size3: "3×3",
  sizeLabel: "Tamaño del cubo",
  modePlay: "Jugar",
  modePlayAbout: "Gíralo como quieras",
  modeGuide: "Resuélvelo conmigo",
  modeGuideAbout: (name) => `${name} te enseña cada giro`,
  modeReal: "Mi cubo de verdad",
  modeRealAbout: "Pinta tu cubo y resuélvelo",
  modeLearn: "Aprende",
  modeLearnAbout: "Un truco cada vez, gana estrellas",
  hello: (name) => `¡Hola! Soy ${name}. ¡A girar!`,
  poke: [
    "¡Gira, gira! 🌀",
    "¡Me encantan los colores! 🎨",
    "¡Tú puedes! 💪",
    "¡Yupi! 🧊",
  ],
  buddyPoke: (name) => `${name}. Tócalo para saludar`,
  moveText: MOVE_ES,
  soFaces: (c) => `para que el ${c} quede delante`,
  soTop: (c) => `para que el ${c} quede arriba`,
  twice: "dos veces",
  scramble: "Mezclar",
  scrambleLabel: "Mezclar el cubo",
  undo: "Deshacer",
  redo: "Rehacer",
  reset: "Nuevo",
  resetLabel: "Dejar el cubo como nuevo",
  pad: "Botones",
  padLabel: "Mostrar u ocultar los botones de giro",
  timer: "Reloj",
  timerLabel: "Mostrar u ocultar el contador y el reloj",
  helpMe: "Ayúdame",
  helpMeLabel: "Resolver este cubo paso a paso",
  moves: (n) => `${n} ${n === 1 ? "giro" : "giros"}`,
  wholeCube: "Todo el cubo",
  faceBtn: (text) => text,
  playTip:
    "Desliza un lado para girarlo. Arrastra alrededor del cubo para girarlo entero.",
  solvedPlay: "¡Resuelto! 🎉",
  solvedPlaySay: (name) => `¡Lo has conseguido! ¡${name} está muy orgulloso!`,
  stagesLabel: "Pasos para resolver el cubo",
  stageOf: (i, n, name) => `Paso ${i} de ${n}: ${name}`,
  stage3: [
    "Cruz blanca",
    "Esquinas blancas",
    "Capa del medio",
    "Cruz amarilla",
    "Aristas amarillas",
    "Esquinas a su casa",
    "Gira las esquinas",
  ],
  stage2: ["Capa blanca", "Esquinas a su casa", "Gira las esquinas"],
  watch: "Enséñame",
  watchLabel: "Ver este giro",
  skip: "Acabar paso",
  skipLabel: "Acaba este paso por mí",
  didIt: "¡Hecho!",
  didItLabel: "He hecho este giro en mi cubo",
  back: "Atrás",
  backLabel: "Volver un giro atrás",
  moveOf: (i, n) => `${i} / ${n}`,
  trick: {
    magic: "Movimiento mágico",
    right: "Truco derecho",
    left: "Truco izquierdo",
    ycross: "Truco de la cruz",
    sune: "Truco remolino",
    corners: "Truco de esquinas",
  },
  say: {
    hold: (c) => `¡Sujeta el cubo con el ${c} arriba!`,
    cross: (c) =>
      `¡Lleva la pieza de color blanco y ${c} a su casa, junto al centro ${c}!`,
    corner: (a, b) =>
      `¡Movimiento mágico! Lleva la esquina de color blanco, ${a} y ${b} a su casa.`,
    flip: "¡Dale la vuelta! Ahora el AMARILLO va arriba.",
    middle: (a, b) => `Haz una T y mete la pieza de color ${a} y ${b} en el medio.`,
    pop: "Esta pieza está atascada. ¡Sácala arriba primero!",
    ycross: "Haz una cruz amarilla arriba con el truco de la cruz.",
    yedges: "Casa las aristas amarillas con sus colores.",
    align: "¡Gira arriba para que todo encaje!",
    yplace: "Manda las esquinas amarillas a su casa.",
    "hold-corner": "Pon una esquina torcida delante, a la derecha.",
    ytwist:
      "¡Movimiento mágico hasta que el amarillo mire arriba! Abajo se desordena: tranquilo.",
    "next-corner": "Gira SOLO arriba para traer la siguiente esquina.",
    layer: (a, b) =>
      `¡Movimiento mágico! Lleva la esquina de color blanco, ${a} y ${b} a su casa.`,
  },
  oops: "¡Uy! Vamos a deshacerlo.",
  oopsDir: "¡Casi! Hacia el otro lado.",
  yay: ["¡Sí! ✨", "¡Genial! 🌟", "¡Muy bien! 👍", "¡Perfecto! 💫"],
  stageDone: (stage) => `${stage}: ¡hecho! 🎉`,
  stageTreat: (name, treats) => `¡${treats} para ${name}!`,
  solvedGuide: "¡Has resuelto el cubo! 🎉",
  solvedGuideBody: (name, treats) =>
    `¡Increíble! ${name} lo celebra comiendo ${treats}.`,
  again: "Otra vez",
  newCube: "Cubo nuevo",
  holdBadge: (top, front) => `Sujétalo: ${top} arriba, ${front} delante`,
  holdBadge2: "Sigue sujetándolo igual",
  realTip: "Haz cada giro en tu cubo de verdad y toca ✓.",
  paintTitle: "Pinta tu cubo",
  paintStep: (i) => `Cara ${i} de 6`,
  paintFace3: [
    "Sujeta el cubo con el BLANCO arriba y el VERDE mirándote. Pinta la cara que ves.",
    "Gira el cubo hacia la izquierda ←. Ahora te mira el ROJO (el BLANCO sigue arriba).",
    "Otra vez hacia la izquierda ←. Te mira el AZUL.",
    "Una vez más a la izquierda ←. Te mira el NARANJA.",
    "Vuelve a poner el VERDE delante e inclina la parte de arriba hacia ti: te mira el BLANCO, con el VERDE abajo.",
    "Inclínalo hacia el otro lado: te mira el AMARILLO, con el VERDE arriba.",
  ],
  paintFace2: [
    "Sujeta el cubo como quieras. Pinta la cara que te mira.",
    "Gira el cubo hacia la izquierda ←. Pinta la cara nueva.",
    "Otra vez hacia la izquierda ←.",
    "Una vez más a la izquierda ←.",
    "Vuelve a la primera cara e inclina la parte de arriba hacia ti.",
    "Inclínalo hacia el otro lado: te mira la cara de abajo.",
  ],
  paletteLabel: "Colores para pintar",
  pickColor: (c) => `Pintar de ${c}`,
  cellLabel: (r, c, col) => `Fila ${r}, columna ${c}: ${col}`,
  blank: "sin pintar",
  next: "Siguiente",
  prev: "Atrás",
  check: "Comprobar mi cubo",
  clearFace: "Borrar",
  left: (n) => `quedan ${n}`,
  paintOk: "¡Tu cubo está perfecto! Vamos a resolverlo.",
  paintErr: {
    unpainted: "Aún hay pegatinas grises. ¡Píntalas todas!",
    count: (over, under) =>
      `Hay demasiadas pegatinas de color ${over} y faltan de color ${under}. ¡Revisa las de color ${over}!`,
    centers:
      "Los colores del centro no cuadran. Pon el BLANCO arriba y el VERDE delante.",
    corner: (cs) => `Esa esquina no puede existir: revisa sus pegatinas de color ${cs}.`,
    edge: (cs) => `Esa arista no puede existir: revisa sus pegatinas de color ${cs}.`,
    twist: "Parece que una esquina está girada. ¡Revisa las esquinas otra vez!",
    flip: "Parece que una arista está dada la vuelta. ¡Revisa las aristas otra vez!",
    parity: "Parece que hay dos piezas cambiadas. ¡Revisa lo que has pintado!",
  },
  paintErrTip:
    "Si todo coincide, puede que tu cubo se desmontara y se montara mal. ¡Pide ayuda a un adulto!",
  and: "y",
  errTitle: "Mmm, vamos a revisar",
  fix: "Arreglarlo",
  learnTitle: "Aprende",
  lesson: (i) => `Lección ${i}`,
  locked: "bloqueada",
  lessonLabel: (i, name, stars, open) =>
    `Lección ${i}: ${name}, ${stars} de 3 estrellas${open ? "" : ", bloqueada"}`,
  lessonIntro: {
    cross:
      "Haz una cruz blanca arriba. Cada arista blanca va junto a su centro del mismo color.",
    corners:
      "¡El movimiento mágico R' D' R D! Pon la esquina debajo de su sitio y repítelo hasta que llegue.",
    middle: "Haz una T con una arista y usa el truco derecho o el izquierdo.",
    ycross:
      "Amarillo arriba. El truco de la cruz F R U R' U' F' hace una cruz amarilla.",
    yedges: "El truco remolino R U R' U R U2 R' cambia las aristas amarillas.",
    yplace: "El truco de esquinas U R U' L' U R' U' L mueve tres esquinas.",
    ytwist:
      "¡Otra vez el movimiento mágico! Repítelo hasta que el amarillo mire arriba y gira solo arriba.",
    layer:
      "Construye la cara blanca con el movimiento mágico R' D' R D, esquina a esquina.",
  },
  letsGo: "¡Vamos! 🚀",
  practice: (i, n) => `Práctica ${i} de ${n}`,
  lessonDone: "¡Lección terminada!",
  lessonStars: (s) =>
    s === 3
      ? "¡Tres estrellas: has hecho todos los giros tú!"
      : s === 2
        ? "¡Dos estrellas! La próxima vez prueba sin mirar."
        : "¡Una estrella! La próxima vez prueba a hacer todos los giros tú.",
  nextLesson: "Siguiente lección",
  totalStars: (n, max) => `⭐ ${n} / ${max}`,
  flatNote: "Vista plana: toca una cara y gírala con las flechas.",
  turnSide: (f) => `Girar ${f}`,
  faceNames: ["ARRIBA", "DERECHA", "FRENTE", "ABAJO", "IZQUIERDA", "ATRÁS"],
  cw: "en el sentido del reloj",
  ccw: "al revés del reloj",
  view3d: "3D",
};

export const TEXTS = { en, es };
